import sqlite3
from werkzeug.security import generate_password_hash

def get_db_connection():
    conn = sqlite3.connect('municipality.db')
    conn.row_factory = sqlite3.Row

    cursor = conn.cursor()
    cursor.execute("PRAGMA foreign_keys = ON")
    conn.commit()
    
    return conn

def create_tables():
    conn = get_db_connection()
    cursor = conn.cursor()
    
    # Enable foreign key support
    cursor.execute("PRAGMA foreign_keys = ON")

    cursor.execute('''
        CREATE TABLE IF NOT EXISTS municipalities (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT UNIQUE NOT NULL
        )
    ''')
    
    # Create user_profiles Table
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS user_profiles (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            username TEXT UNIQUE NOT NULL,
            password TEXT NOT NULL,
            full_name TEXT NOT NULL,
            email TEXT UNIQUE NOT NULL,
            phone_number TEXT UNIQUE NOT NULL,
            address TEXT NOT NULL,
            municipality_id INTEGER NOT NULL,
            role TEXT CHECK( role IN ('Citizen', 'Municipality Employee') ) DEFAULT 'Citizen',
            FOREIGN KEY (municipality_id) REFERENCES municipalities(id) ON DELETE CASCADE
        )
    ''')
    
    # Create Fees Installments Requests Table
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS fees_installments_requests (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id INTEGER NOT NULL,
            municipality_id INTEGER NOT NULL,
            applicant_name TEXT NOT NULL,
            address TEXT NOT NULL,
            phone_number TEXT NOT NULL,
            property_number TEXT NOT NULL,
            section_number TEXT NOT NULL,
            area TEXT NOT NULL,
            total_fees TEXT NOT NULL,
            installment_option TEXT NOT NULL,
            installments TEXT NOT NULL,
            fee_statement_path TEXT NOT NULL,
            status TEXT DEFAULT 'Pending',
            submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            reviewed_at TIMESTAMP,
            FOREIGN KEY (user_id) REFERENCES user_profiles(id) ON DELETE CASCADE,
            FOREIGN KEY (municipality_id) REFERENCES municipalities(id) ON DELETE CASCADE
        )
    ''')

        # Create Statement Requests Table
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS statement_requests (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id INTEGER NOT NULL,
            municipality_id INTEGER NOT NULL,
            full_name TEXT NOT NULL,
            address TEXT NOT NULL,
            phone_number TEXT NOT NULL,
            document_type TEXT NOT NULL,
            purpose TEXT NOT NULL,
            submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            status TEXT DEFAULT 'Pending',
            FOREIGN KEY (user_id) REFERENCES user_profiles(id) ON DELETE CASCADE,
            FOREIGN KEY (municipality_id) REFERENCES municipalities(id) ON DELETE CASCADE
        )
    ''')
    
    # Create Disabled Person Request Table
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS disabled_person_requests (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id INTEGER NOT NULL,
            municipality_id INTEGER NOT NULL,
            full_name TEXT NOT NULL,
            address TEXT NOT NULL,
            phone_number TEXT NOT NULL,
            disability_type TEXT NOT NULL,
            medical_report_path TEXT NOT NULL,
            submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            status TEXT DEFAULT 'Pending',
            FOREIGN KEY (user_id) REFERENCES user_profiles(id) ON DELETE CASCADE,
            FOREIGN KEY (municipality_id) REFERENCES municipalities(id) ON DELETE CASCADE  
        )
    ''')
    
    # Create Shakwa aw Moraja3a Table
    # cursor.execute('''
    #     CREATE TABLE IF NOT EXISTS shakwa_moraja3a_requests (
    #         id INTEGER PRIMARY KEY AUTOINCREMENT,
    #         user_id INTEGER NOT NULL,
    #         full_name TEXT NOT NULL,
    #         email TEXT NOT NULL,
    #         phone_number TEXT NOT NULL,
    #         message TEXT NOT NULL,
    #         submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    #         status TEXT DEFAULT 'Pending',
    #         FOREIGN KEY (user_id) REFERENCES user_profiles(id) ON DELETE CASCADE
    #     )
    # ''')

    cursor.execute('''
        CREATE TABLE IF NOT EXISTS municipal_clearance_requests (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id INTEGER NOT NULL,
            municipality_id INTEGER NOT NULL,
            full_name TEXT NOT NULL,
            address TEXT NOT NULL,
            phone_number TEXT NOT NULL,
            request_type TEXT NOT NULL,
            notes TEXT,
            document_1 TEXT,
            document_2 TEXT,
            document_3 TEXT,
            document_4 TEXT,
            submission_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (user_id) REFERENCES user_profiles(id) ON DELETE CASCADE,
            FOREIGN KEY (municipality_id) REFERENCES municipalities(id) ON DELETE CASCADE
        )
    ''')

    


    
    conn.commit()
    conn.close()

def insert_municipalities():
    conn = get_db_connection()
    cursor = conn.cursor()
    
    municipalities = [
        "Beirut",
        "Jbail",
        "Edde",
        "Ehmej",
        "Bejje",
        "Blat",
        "Tartij",
        "Jaj",
        "Halat",
        "Aaqoura",
        "Aamchit",
        "Aannaya - Kfarbaal",
        "Fatre",
        "Fidar",
        "Qartaba",
        "Lassa",
        "Ain el Ghouaibe",
        "Laqlouq",
        "Mghaira",
        "Monsef",
        "Maifouq - Qattara",
        "Nahrh Ibrahim",
        "Lehfed",
        "Majdel",
        "Yanouh - Hedayne",
        "Mazraat Es Siyad",
        "Ras Osta",
        "Mechane",
        "Hjoula",
        "El Houssoun",
        "Hosrayel",
        "Barbara",
        "Bechtelida - Fidar",
        "Afqa",
        "Almat Ej Jnoubiye - ech Chemaliye - Ain Souane",
        "MechMech Jbeil",
        "Ghabate - Rouaiss",
        "Ghalboun",
        "Jounieh",
        "Balloune",
        "Bouar",
        "Jdaidet Ghazir",
        "Jitta",
        "Jouret Bedrane",
        "Jouret Et Tormoss",
        "Hrajel",
        "Hsayn",
        "Hayata",
        "Darayia Kesrwane",
        "Daraaoun - Harissa",
        "Delbta",
        "Zouk Mosbeh",
        "Zouq Mkayel",
        "Raashine",
        "Raifoun",
        "Shaile",
        "Chnanaair",
        "Safra kesrwane",
        "Tabarja - Kfar Yassine",
        "Aajaltoun",
        "El Aazra et el Aazr",
        "Aaramoun Kesrwane",
        "Aachqout",
        "El Aaqaybe Kesrouane",
        "Ain Er Rihane",
        "Aintoura",
        "Ghbale",
        "Ghazir",
        "Ghosta",
        "Ghine",
        "Faraiya",
        "Faitroun",
        "Qlaiaat",
        "Kfardibiane",
        "Kfour",
        "Mairouba",
        "Yahchouch",
        "Maaysra",
        "Beqaatet Aachqout",
        "Ouata Ej Jaouz",
        "Zaaitra",
        "Fatqa",
        "Chahtoul - Jouret Mhad",
        "Batha",
        "Zeitoun",
        "Ghadras",
        "Bqaatouta",
        "Kfar Tay",
        "Bzoummar",
        "Edma et Dafne",
        "Jdaide - Baouchriye - Sad el Baouchriye",
        "Antelias - Naqqach",
        "Bteghrine",
        "Borj Hammoud",
        "Broumana",
        "Baskinta",
        "Bsalim - Majzoub - Mezher",
        "Baabdat",
        "Bikfayia - Mhaydse",
        "Biaqout",
        "Beit Chebab - Chaouiye - Qnaitra",
        "Beit Ech-Chaar - Mazraat El Hdaira",
        "Ain Saade",
        "Bqennaya - Jall Ed Dib",
        "Khenchara - Jouar",
        "Dekouane",
        "Douar",
        "Er Rabie",
        "Roumie",
        "Zaraaoun",
        "Zalqa - Amaret Chalhoub",
        "Zikrit",
        "Bhersaf - Saqeit El Misk",
        "Sinn el Fil",
        "Choueir - Ain Es Sindiane",
        "Dbaiye - Zouk el Kharab - Haret el Bellane - Aaoukar",
        "Dahr Es Souane Meten",
        "Aairoun",
        "Ain Es Safsaf el meten - Mar Mkhayel Bnabil",
        "Aintoura el meten",
        "Ouata El Mrouj - Ghabet Bolonia",
        "Fanar",
        "Qornet Chahouane - Ain Aar - Beit El Koukko - Hbous",
        "Qaaqour",
        "Kfartay",
        "Kfar Aaqab",
        "Mar Chaaya - Mzakke",
        "Mar Mousa Ed Daouar",
        "Mtein - Mcheikha",
        "Mrouj",
        "Mazraat Yachoua",
        "Mansouriye - Mkalless - Daychouniye",
        "Nabay",
        "Majdel Tarchich",
        "Marjaba",
        "Qennabet Broummana",
        "Ghabe",
        "Aiyoun",
        "Dik El Mehdi - Deir Tamich",
        "Aatchane",
        "Beit Meri",
        "Baabda",
        "Btekhnay",
        "Borj el Brajne",
        "Bzebdine",
        "Bsaba Baabda",
        "Boutchai - Merdache",
        "Baalchmay",
        "Tarchich",
        "Jouar el Haouz",
        "Jouret Arsoun",
        "Hazmiye",
        "Hasbaiya el Metn",
        "Hadet",
        "Hammana",
        "Khraibe Baabda",
        "Deir el Harf",
        "Ras el Harf",
        "Ras el Metn",
        "Rouisset el Ballout",
        "Chbaniye",
        "Chiayah",
        "Arayia",
        "Aarbaniye - Dlaibe",
        "Ghobeire",
        "Falougha",
        "Furn ech Chebak",
        "Qoubbeiaa",
        "Qirtada",
        "Qornayel",
        "Qraiye",
        "Qsaibe",
        "Qalaa",
        "Kfar Selouane",
        "Kfarchima",
        "Tahouitet el Ghadir - Lailake - Mraije",
        "Ouadi Chahrour el Soufla",
        "Ouadi Chahrour el Olia",
        "Haret Hraik",
        "Haret es Set",
        "Arsoun",
        "Chouit",
        "Aabadiye",
        "Bmariam",
        "Salima Baabda",
        "Aley",
        "Ighmid",
        "Btater",
        "Bhamdoun ed Dayaa",
        "Bhamdoun el Mhatta",
        "Bdedoun",
        "Bedghane",
        "Bsatine",
        "Bsous",
        "Bchamoun",
        "Bkhechtay",
        "Btalloun",
        "Blaibel",
        "Bmekkine",
        "Bmahray",
        "Bnaiye",
        "Baissour",
        "Houmal",
        "Dfoun",
        "Deir Qoubil",
        "Rechmaiya",
        "Remhala",
        "Ramliye",
        "Rouisset en Naamane",
        "Souq el Gharb",
        "Charoun",
        "Chanay",
        "Chartoun",
        "Chemlane",
        "Choueifat",
        "Sofar",
        "Aaramoun",
        "Aitat",
        "Ainab",
        "Ain ej Jdide",
        "Ain Al Saydeh",
        "Mazraat Al Souaydane",
        "Ain er Remmane",
        "Ain Anoub",
        "Ain Ksour",
        "Qmatiye",
        "Kahale",
        "Kfar Aamaiy",
        "Kaifoun",
        "Mejdel Baana",
        "Majdalaya",
        "Mechrefe",
        "Mansouriye bhamdoun - Ain el Marj",
        "Baaouerta",
        "Rejme",
        "Taazniye",
        "Aabey - Ain Drafil",
        "Kfar Matta",
        "Ghaboun",
        "Daqqoun",
        "Beit ed Dine",
        "Bater",
        "Barouk - Fraidiss",
        "Batloun",
        "Barja",
        "Bsaba",
        "Bchatfine",
        "Boutme",
        "Baasir",
        "Baadarane",
        "Baaqline",
        "Bire",
        "Jahliye",
        "Jbaa",
        "Jadra",
        "Jdaide chouf",
        "Joun",
        "Jiye",
        "Haret Jandal",
        "Hasrout",
        "Khraibe chouf",
        "Daraiya",
        "Damour",
        "Dibbiye",
        "Dalhoun",
        "Dmit",
        "Deir Dourite",
        "Deir el Qamar",
        "Deir Qouche",
        "Rmaile",
        "Zaarouriye",
        "Sibline",
        "Sirjbal",
        "Samqaniye",
        "Chhim",
        "Dahr el Mghara",
        "Aanout",
        "Aatrine",
        "Aammatour",
        "Aammiq chouf",
        "Ain Bal",
        "Ain Zhalta",
        "Ain Ouzain",
        "Ain Qeni",
        "Gharife",
        "Faouarat Jaafar",
        "Ketermaya",
        "Kahlouniye chouf",
        "Kfar Him",
        "Kfar Qatra",
        "Kfar Nabrakh",
        "Kfar Niss",
        "Knisse chouf",
        "Majdel el Meouch",
        "Moukhtara",
        "Mristi",
        "Mazboud",
        "Mazraat ech Chouf",
        "Mazraat ed Dahr",
        "Mechref",
        "Mtoulle",
        "Maaser Beit ed Dine",
        "Maasser ech Chouf",
        "Mghairiye Chouf",
        "Naame Haret en Naame",
        "Niha",
        "Ouadi es Sitt",
        "Quardaniye",
        "Ouarhaniye",
        "Kfar Faqoud",
        "Brih",
        "Borjein",
        "Ain el Haour",
        "Zahle Maalaqa",
        "Ablah",
        "Bar Elias",
        "Bouarej",
        "Terbol",
        "Taalabaya",
        "Taanayel",
        "Jdita",
        "Haouch Moussa Anjar",
        "Raait",
        "Deir el Ghazal",
        "Haret el Fikani",
        "Rayak - Houch Hala",
        "Saadnayel",
        "Chtaura",
        "Aali en Nahri",
        "Fourzol",
        "Qaa er Rim",
        "Qabb Elias",
        "Koussaya",
        "Kfar Zabad",
        "Majdel Anjar",
        "Mreijat",
        "Meksi",
        "Nabi Aila",
        "Niha zahle",
        "Massa",
        "Ain Kfar Zabad",
        "Hazerta",
        "Baalbek",
        "Iaat",
        "Betdaai",
        "Bednayel",
        "Barqa",
        "Britel",
        "Bechouat",
        "Boudai",
        "Tammine et Tahta",
        "Tamnine El Faouqa",
        "Jabboule",
        "Hadath Baalbek",
        "Harabta",
        "Hizzine",
        "Haouch Barada",
        "Haouch Tall Safiye",
        "Khraibe",
        "Douris",
        "Deir El Ahmar",
        "Ras Baalbek",
        "Saraain et Tahta",
        "Saraain el Faouqa",
        "Saaide",
        "Chaat",
        "Chlifa",
        "Chmistar",
        "Taraiya",
        "Talia",
        "Taibe Baalbek",
        "Aarsal",
        "El Ain",
        "Ainata",
        "Fakehe - Jdaide",
        "Flaoui",
        "El Qaa",
        "Qsarnaba",
        "Laboue",
        "Majdaloun",
        "Maqne",
        "Nabi Chit",
        "Nabi Osmane",
        "Nahle",
        "Wadi Faara",
        "Yammoune",
        "Younine",
        "Houch Er Rafqa",
        "Ram - Joubaniyeh",
        "Zabboud",
        "Khodor",
        "Haouch Snaid",
        "Qarha",
        "Halbata",
        "Janta",
        "Jabaa",
        "Qalb es Sabaa",
        "Haouch En Nabi",
        "Maarboun",
        "Mazraat al Ramassy",
        "Nabha Ed-Damdoum",
        "Qiddam",
        "Nabha Al Mohfara",
        "Qlaile-Harfouch",
        "Toufiqiye",
        "Zrazir",
        "Joub Jannine",
        "Bab Maraa",
        "Baaloul",
        "Houch el Harime",
        "Khirbet Qanafar",
        "Khiara",
        "Sohmor",
        "Soultan Yaaqoub Aradi",
        "Saghbine",
        "Souairi",
        "Aana",
        "Aammiq",
        "Aitanit",
        "Ain Zebde",
        "Ghazze",
        "Qaraoun",
        "Kamed el Laouz",
        "Kafraiya West Bekaa",
        "Lala",
        "Libbaya",
        "El Marj",
        "Machgara",
        "Manara Hammara",
        "Mansoura",
        "Yohmor West Bekaa",
        "Meidoun",
        "Ain et Tine West Bekaa",
        "Qillaya",
        "Raouda Istabl",
        "Tall Znoub",
        "Rachaiya",
        "Bakka",
        "Bakkifa",
        "Beit Lahia",
        "Bire rachaya",
        "Tannoura",
        "Haloua",
        "Haouch El Qinnabeh",
        "Khirbet Rouha",
        "Deir el Aachayer",
        "Rafid",
        "Dahr el Ahmar",
        "Aaqbe",
        "Aita el Foukhar",
        "Aaiha",
        "Ain Hircha",
        "Ain Aarab",
        "Ain Aata",
        "Kfar Danis",
        "Kfar Qouq",
        "Kfar Mechki",
        "Kaoukaba",
        "Majdal Balhis",
        "Mhaidse",
        "Mdoukha",
        "Yanta",
        "Selsata Mazraat Dier el Aachayer",
        "Hermel",
        "Qasr",
        "Fissane",
        "Jouar El Hachich",
        "Kouakh",
        "Chouaghir",
        "Darb es Sim",
        "Arzay",
        "Aabra",
        "Ghassaniye",
        "Hlaliye Saida",
        "Qraiye Saida",
        "Qennarit",
        "Najjaryie",
        "Ain Ed Delb",
        "Arkey",
        "Bramiye",
        "Khartoum",
        "Bnaafoul",
        "Maamriye",
        "Qaaqaaii es Snoubar",
        "Majdelyoun",
        "Barti",
        "Loubiye",
        "Salhiye",
        "Tanbourit",
        "Aaqtanit",
        "Aaddoussiye",
        "Zaita",
        "Bqosta",
        "Mazraat Arab Tobbaya",
        "Kfar Beit",
        "Hajje",
        "Jezzine - Ain Majdalain",
        "Kfar Houne",
        "Rihane Jezzine",
        "Bkassine",
        "Qaitoule",
        "Aaramta",
        "Aaichiye",
        "Mlikh",
        "Roum",
        "Jernaya",
        "Louaiziye",
        "Lebaa",
        "Sfarai",
        "Midane",
        "Sejoud",
        "Jarmaq",
        "Wadi Jezzine",
        "Aazour",
        "Aariye",
        "Haitoura",
        "Benouati",
        "Bteddine el Loqch",
        "Mjaydel",
        "Maknouniye",
        "Sidoun",
        "Zhalta",
        "Sabah",
        "Karkha",
        "Kfar Falous",
        "Machmouche",
        "Sniye",
        "Kfar Jarra",
        "Deir El Qattine - Haidab",
        "Homsiye",
        "Raimat - Deir Chkedif",
        "Sour",
        "Jouaiya",
        "Qana",
        "Maarake",
        "Aabbassiye",
        "Chehabiye",
        "Borj ech Chmali",
        "Chahour",
        "Srifa",
        "Bazouriye",
        "Ain Baal",
        "Deir Qanoun en Nahr",
        "Tair Debba",
        "El Kleile",
        "Borj Rahhal",
        "Toura",
        "Siddiqine",
        "Mjadel",
        "Majdel Zoun",
        "Maaroub",
        "Tair Filsay",
        "Bourghliye",
        "Barich",
        "Bani Sakher",
        "Aaitit",
        "Naqoura",
        "Chaaitiyeh - Malkeit es Sahel",
        "Mansouri",
        "Yarine",
        "Deir Qanoun ras el aain",
        "Deir Kifa",
        "Aalma ech Chaab",
        "Hannaouiye",
        "Debaal",
        "Tair Harfa",
        "Halloussiye",
        "Bafliye",
        "Salaa",
        "Deir Aamess",
        "Batouliye",
        "Rmadiyeh",
        "Zabqine",
        "Jebbain",
        "Boustane Sour",
        "Marouahine",
        "Mahrouneh",
        "Jbal el Botm",
        "Bedias",
        "Chamaa",
        "Chihine",
        "Ynouh",
        "Mazraat Mechref",
        "Rechkananey",
        "Derdghaiya",
        "Biyad Sour",
        "Haumeiri",
        "Hanniye",
        "Arzoun",
        "Knisse Sour",
        "Dhaira",
        "Jannata",
        "Nabatiye el Tahta",
        "Nabatiye el Faouqa",
        "Jibchit",
        "Insar",
        "Habbouch",
        "Harouf",
        "Doueir El Nabatieh",
        "Kfar Roummane",
        "Jbaa El Nabatieh - Aain Bou Souar",
        "Kfar Tebnit",
        "Arab Salim",
        "Aabba",
        "Kfar Sir",
        "Nmairiye",
        "Deir ez Zahrani",
        "Qaaqaait ej Jisr",
        "Ain Qana",
        "Qsaibe El Nabatieh",
        "Maifadoun",
        "Aadchit ech Chqif",
        "Sir el Gharbiye",
        "Houmine el Faouqa",
        "Houmine et Tahta",
        "Jarjouaa",
        "Kfour El Nabatieh",
        "Zefta",
        "Charqiye",
        "Zaoutar ech Charqiye",
        "Zaoutar el Gharbiye",
        "Yohmor",
        "Aarnoun",
        "Zebdine El Nabatieh",
        "Sarba El Nabatieh",
        "Braiqaa",
        "Kfar Fila",
        "Roumine",
        "Choukine",
        "Aazze",
        "Sinai",
        "Kfaroue",
        "Toul",
        "Bent Jubail",
        "Aaitaroun",
        "Chaqra - Doubiye",
        "Tebnine",
        "Braachit",
        "Aainata",
        "Aita Ech Chaab",
        "Rmaich",
        "Hariss",
        "Khirbit Silim",
        "Maroun er Ras",
        "Kafra Bent Jbeil",
        "Kounine",
        "Ain Ebel",
        "Yaroun",
        "Yater",
        "Haddatha",
        "Beit Lif",
        "Deir Ntar",
        "Kfar Dounine",
        "Debl Oummiya",
        "Tiri",
        "Aayta ej Jabal Zott",
        "Rachaf",
        "Ramiye",
        "Soultaniye",
        "Beit Yahnoun",
        "Hanine",
        "Qalaouiye",
        "Jmaijime",
        "Safad el Battikh",
        "Sribbine",
        "Borj Qalaouiye",
        "Froun",
        "Qaouzah",
        "Ghandouriye Bent Jbeil",
        "Chebaa",
        "Hasbaiya",
        "Kfar Chouba",
        "Hebbariye",
        "Kfair",
        "Rachaiya el Foukhar",
        "Ain Qenya",
        "Chouaia",
        "Kaoukaba Hasbaya",
        "Mimes",
        "Khalouat Hasbaya",
        "Kfar Hamam",
        "Mari - Majidiyeh Hasbaiya",
        "Marj Ez Zouhour Dnaibe",
        "Fardis",
        "Khiam",
        "Meiss ej Jabal",
        "Taibe Marjaayoun",
        "Markaba",
        "Jdaideh Marjaayoun",
        "Houla",
        "Kfar Kila",
        "Blida",
        "Majdel Silim",
        "Aadaisse",
        "Qlaiaa",
        "Deir Mimas",
        "Qabrikha",
        "Ibl es Saqi",
        "Blat Marjaayoun",
        "Rabb et Talatine",
        "Qantara",
        "Dibbine",
        "Touline",
        "Tallouse",
        "Souane Marjaayoun",
        "Beni Haiyane",
        "Deir Siriane",
        "Borj El Mlouk",
        "Aadchit el Qoussair",
        "Ouazzani",
        "Tripoli",
        "El Mina",
        "Qalamoun",
        "Tannourine",
        "Batroun",
        "Chekka",
        "Douma",
        "Hamat",
        "Hardine - Beit Kassab",
        "Aabrine",
        "Kfour El Aarbi",
        "Bcheale",
        "El Heri",
        "Ras Nahhach",
        "Kfar Aabida",
        "Kfar Helda",
        "Chabtine",
        "Assia",
        "Koubba",
        "Bqosmaiya",
        "Selaata",
        "Zane",
        "Kfar Hay",
        "Edde el Batroun",
        "Jrane",
        "Ijdabra",
        "Kour",
        "Zgharta",
        "Miziara",
        "Arde",
        "Rachaaine",
        "Miryata - El Qadriye",
        "Kfar Sghab",
        "Sebaal",
        "Aalma",
        "Haret al Fouwar",
        "Chaqdouf",
        "Majdalaya zgharta",
        "Toula zgharta",
        "Mazraat Et Toufah",
        "Aachach",
        "Karm Sadde",
        "Seraal",
        "Kfar Dlaqous",
        "Ain Tourine",
        "Aitou",
        "Kafar Zeina",
        "Aarbet Qozhaiya",
        "IAAL",
        "Bouhairet Toula",
        "Kfar Hata Zgharta",
        "Qarah Bach",
        "Aarjess",
        "Kfar Yachit - Bsebaal",
        "Raskifa",
        "Baslouqit",
        "Bnechaai",
        "Kfar Fou",
        "Bcharre",
        "Hadchit",
        "Hasroun",
        "Bqaa Kafra",
        "Bazaoun",
        "Bqerqacha",
        "Hadet Ej jebbe",
        "Tourza",
        "Qnat",
        "Barhalioun",
        "Aabdine Bcharre",
        "Bebnine",
        "Fnaideq",
        "Mechmech",
        "Qoubaiyat",
        "Aakkar El Attiqa",
        "Berqayel",
        "Halba",
        "Rahbe",
        "Ain al zahab",
        "Ouadi Ej jamous",
        "Takrit",
        "Bire Akkar",
        "Minyara",
        "Andqat",
        "Beino - Qboula",
        "Machta Hammoud",
        "Chadra",
        "Bqerzala",
        "Hrar",
        "Aaiyat",
        "Machha",
        "Bezbina",
        "Machta Hassan",
        "Qabaait",
        "Beit Mellat",
        "Mqaible",
        "Aaidamoun - Cheikhlar",
        "El Haissa",
        "Jdeidet El Qaitaa",
        "Jdaidet Ej Joumeh",
        "Tall Aabbas el Gharbi",
        "Ed Daoura",
        "Tal Meaayan",
        "Qarqaf",
        "Cheik Mohammad",
        "El Houaich",
        "Zouq el Hassineh",
        "Cheikh Taba",
        "El Aabboudiye",
        "Bzal",
        "Jebrayel",
        "Khreibet ej Jindi",
        "El Qlaiaat",
        "Es Souaisse",
        "Tall Bire",
        "El Mqaiteaa",
        "Mhamra",
        "El Borj Akkar",
        "Majdla",
        "Mazraat Al Balde",
        "Mechaeilha Hakour",
        "Chane",
        "Tashea",
        "Ain Yaaqoub",
        "Sfaynet El-Qaitaa",
        "Kawashra",
        "Sindianet Zeidane",
        "Karm el Aasfour - Beit Ghattas - Mazraat En-Nahriyeh",
        "Kfartoun",
        "Akroum",
        "Ain ez Zeit - Kafr El Ftouh",
        "Tleil",
        "Kousha",
        "Zouk Haddara",
        "Ilat",
        "Memnaa",
        "Borj el Arab",
        "Haizouq",
        "Daousse Baghdadi",
        "Al-Massoudieh",
        "El Aayoun",
        "Aaouinat",
        "Deir Dalloum",
        "Zouarib",
        "El Qantara",
        "Charbila",
        "Qraiyat",
        "Mar Touma",
        "Khirbet Daoud",
        "Deir Janine",
        "Dibbabiye",
        "Hmaireh Aakkar",
        "Khirbet Char",
        "Nfaisseh",
        "Qinye",
        "Qoubbet Chamra",
        "Saissouq",
        "Beit el Haj",
        "Rihaniye",
        "Fsiqine - Ain Echma -Ain Tinta",
        "Shattaha",
        "Dahr Laissineh",
        "Doueir Aadouiye",
        "Tall Aabbas Ech-Charqi",
        "Aayoun El Ghezlane",
        "Mouanse",
        "Sfinet ed Dreib",
        "Kouikhat",
        "Nahriye - Boustane El Herch",
        "Aarqa",
        "Beit Younes",
        "Amaret el Baykat",
        "Amioun",
        "Enfe",
        "Kousba",
        "Dedde",
        "Kfar Aaqqa",
        "Kfar Hazir",
        "Dar Baachtar",
        "Bechmizzine",
        "Ras Maska",
        "Kefraiya",
        "Btourram",
        "Fiaa",
        "Barsa",
        "Bsarma",
        "Qalhat",
        "Batroumine",
        "Kfar Hata",
        "Bziza",
        "Ain Aakrine",
        "Btouratij",
        "Rechdibbine",
        "Aafsdiq",
        "Bdibba",
        "Kfar Saroun",
        "Metrit",
        "En Nakhle",
        "Ijdabrine",
        "Kfar Qahel",
        "Majdel el Koura - Zakzouk",
        "Btaaboura",
        "Bednayel el koura",
        "Kaftoun",
        "Bkeftine",
        "Dar Chmizzine",
        "El Minie - En Nabi Youchaa",
        "El Beddaoui - Ouadi En Nahle",
        "Bakhaoun",
        "Sir Ed Danniye",
        "Sfire",
        "Deir Amar",
        "Bhannine El Minieh - Mazraat Aartoussi - Er Rihaniye El Minieh",
        "Bqarsouna",
        "Qattine El Minieh",
        "Bqaa Safrin",
        "Qarsita",
        "Kfar Habou",
        "Aassoun",
        "Btermaz",
        "Tarane",
        "Nemrine",
        "Izal",
        "Beit El Faqs",
        "Azqey",
        "Karm El - Mohr",
        "Mrah Es Sreij",
        "Haql El Aazime",
        "Deir Nbouh",
        "Kfar Bebnine",
        "Markabta",
        "Amar",
        "Ain Et Tine",
        "Kfar Chillane",
        "Mrah Es Sfire",
        "Borj El Yahoudiye",
        "Harf es siyad",
        "Behouaita - Afqa El Minieh - Bchennata",
        "El Hazmiye",
        "Saida",
        "Ghaziye",
        "Sarafand",
        "Aadloun",
        "Zrariye",
        "Saksakiye",
        "Kharayeb Saida",
        "Maghdouche",
        "Babliye",
        "Toufahta",
        "Haret Saida",
        "Merouaniye",
        "Aanqoun",
        "Miyeh ou Miyeh",
        "Kfar Melki Saida",
        "Kfar Hatta",
        "Bissariye",
        "Insariye",
        "Kaouthariyet es Siyad",
        "Chatine",
        "Deir Billa",
        "Thoum",
        "Zellaya",
        "Aalmane Ech Chouf - Mazraat El Barghoutiye",
        "Hamlaya",
        "Mazraat Sejoud",
        "Bane",
        "Knisse",
        "Moqraq",
        "Anane",
        "Dellafi",
        "Nasriyet Zahle",
        "Darayia - Bchannine",
        "Kfar Chellal",
        "Naffakhiye",
        "Ain Dara",
        "Silfaya",
        "Sarahmoul",
        "Jdaidet Harharaya - Qattine",
        "Amayer - Rajm Issa",
        "El Majdal",
        "El Hichi",
        "Wadi Khaled",
        "Aarab Jourmnaya - El Rama",
        "Khat Petrol",
        "Rmah",
        "Sahle",
        "Idbil",
        "Berbara",
        "Dahr Qanbar",
        "Daghle",
        "Mounjez",
        "Ghzaile",
        "Fard",
        "Kroum el Arab",
        "El Qorne",
        "Al Ansar Baalbek"
    ]
    
    for name in municipalities:
        cursor.execute("INSERT OR IGNORE INTO municipalities (name) VALUES (?)", (name,))
    
    conn.commit()
    conn.close()

def user_exists(cursor, email, phone_number):
    cursor.execute("SELECT 1 FROM user_profiles WHERE email = ? OR phone_number = ?", (email, phone_number))
    return cursor.fetchone() is not None



def fetch_users():
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute("SELECT id, username, full_name, email, phone_number, address, role, password FROM user_profiles")
    rows = cursor.fetchall()
    conn.close()
    
    print("\nUser Profiles:")
    for row in rows:
        print(row)


if __name__ == "__main__":
    create_tables()
    insert_municipalities()
    fetch_users()
    print("Database tables and sample users initialized successfully.")